version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "monthly"
    reviewers:
      - "CorieW"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: increase